language: minimal
dist: xenial
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
env:
  global:
  - secure: jIHHQm1q7jxDjiB9NoBXWU00eYdhFlOKRJWI0/B8th0PyFuUwemmVy7NjyWmgObz9kZXEG72XkyJj9P43z4AQKkf9rE8/jmngp8zZ4NCGawDw9OAnTc78z/bkGvPBUuHLe7fNZm4KFUmdFJ8JQr4JLtVBaJggraCxI+S8Q5VFdJMoOqTtRuE5TtdTilF80L4lGkTyYGxZnRsto1jTmQ+wjAdfpcrqz/wbyV6xeeiEMc/hlhLxI4F7LUjJPnBI1zl66gsUoOTIBgSSyz8TS2ClxkBIFetLu8uNZx4ROG+nlEmvvc6IAP/snqcFbZaMx5XAEjp0gLXitdQEv/6eVXPkEGom4kti/bi/i7j86V2G5NpXfl/3wUeW/3GRxvhit9xfu9WIhXEJKtePHV6abh7oPUNbTaB4jcIpZAgUOfhj+L30dA42WLUCsuBsiNEWFj/GCdZKZ0CStFRVsTHN6ofFFpGpzzKFrU0+1LpnuXYcb9jGxJ9G5UOSp3cysB1QB7GiGmXR21w6Mtss3z4c+uD4h3N5x6+KTEHJ1k7yBBG1ikbVVmscWWcb/FW16TdVjCo9nv2nU7n16asN72BnlGvD3YAV6BQvNEDLd6GHPJ7rTFv94RgYaOSG3LAsOyZoQhU6hVROHEFbWKpEByyDld6UOYuAYhvoQTByiOrMABZuaY=
  - secure: kboSZAcMbiuRoK2Ojp60d9IM2VSpICCp6kZIISDGBPQQrJWFxbOlTTU4aF3seBCsR5IAxtz8V4N41gzVgZMuafLfQWEH2ejUI5zN6ej3wXV1U+3Kzo/eQ42U9o7NQCSnNU+fE29KkerJsdRIP68n1X1fv0TNbIBFG7EpU8J6dpzMBtxe9BCVPNzoIGmU+JHQF6i/T8Jl0vehuUeen7+8N/SAe/AP/ABH7Lgry5Y3E8XqfMf+MokDuzEvajorZUFKan8ldb3Z6zRw/suPi36z+2HN+6eHtevbBP6QnYaxC40g8UT8+vW7rtJ9+91lXOWTKb4VUNhlno/HUVUSLPyBqCgS6jfWn60iPEDZF0kUIRH/nBVLAyFKN6/wlxDj0zsIvoBOVTLgsmL1ZxVe/qFg6wI6ejDYzQvTxOmyRR7yFHQSlj8bN9P40XBt7iZVVC3dAeidpK92fsW8w/KgbAm6M489QXGF6LuRXWP2RWC/ydutW7yDxMYgbkK0/mnK2cPCSyjqzJDpsL2Ajz1fhJb1maCFQ1H3IG3vD+ZkLr22VhhO6zFttHLMMXdcgouySAEiCojyYWr3XmLDaUEFBjsSvvbbRPoOqdnZnW5+y5LJfxhEJ/ACCBcu+9wxBk763/HLutQ8tU/STTF/X8U/LpX2ZDkQlBC8FGXqgw/SZjGhFzo=
before_install:
- echo "options timeout:5" | sudo tee -a /etc/resolvconf/resolv.conf.d/tail
- echo "options attempts:5" | sudo tee -a /etc/resolvconf/resolv.conf.d/tail
- sudo service resolvconf restart
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo systemctl restart docker
- sudo docker run --privileged linuxkit/binfmt:v0.6
install:
- docker image pull moby/buildkit:master
before_script:
- rm -Rf target/*.tar
- mkdir -p target
jobs:
  include:
  - stage: build
    script: "./build.sh master"
